# coding: utf-8

"""
    OpenCARWINGS API

    API to get information about cars. API Token is accessible from your account settings

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Patched for use inside Home Assistant:
      - SSL context creation (ssl.create_default_context / load_default_certs) is
        deferred and executed in a thread executor instead of on the event loop,
        to avoid HA's "Detected blocking call" warning.
      - RESTClientObject can optionally be handed an existing aiohttp.ClientSession
        (e.g. Home Assistant's shared session via async_get_clientsession(hass)).
        When a session is supplied, this client never builds its own
        TCPConnector/SSLContext/ClientSession at all, and does not close the
        session on close() (HA owns its lifecycle).
"""  # noqa: E501

import asyncio
import io
import json
import re
import ssl
from typing import Any, Dict, Optional, Union

import aiohttp
import aiohttp_retry

from opencarwings_client.exceptions import ApiException, ApiValueError

RESTResponseType = aiohttp.ClientResponse

ALLOW_RETRY_METHODS = frozenset({'DELETE', 'GET', 'HEAD', 'OPTIONS', 'PUT', 'TRACE'})


class RESTResponse(io.IOBase):

    def __init__(self, resp) -> None:
        self.response = resp
        self.status = resp.status
        self.reason = resp.reason
        self.data = None

    async def read(self):
        if self.data is None:
            self.data = await self.response.read()
        return self.data

    @property
    def headers(self):
        """Returns a CIMultiDictProxy of response headers."""
        return self.response.headers

    def getheaders(self):
        """Returns a CIMultiDictProxy of the response headers; use ``headers`` instead."""
        return self.response.headers

    def getheader(self, name, default=None):
        """Returns a given response header; use ``headers.get()`` instead."""
        return self.response.headers.get(name, default)


class RESTClientObject:

    def __init__(
        self,
        configuration,
        *,
        session: Optional[aiohttp.ClientSession] = None,
    ) -> None:
        """
        :param configuration: the generated Configuration object.
        :param session: an already-constructed aiohttp.ClientSession to reuse
                         (e.g. Home Assistant's shared session obtained via
                         ``homeassistant.helpers.aiohttp_client.async_get_clientsession(hass)``).
                         When provided, this client will never build its own
                         SSLContext/TCPConnector/ClientSession, and will not
                         close the session in ``close()`` — the caller (HA)
                         owns that session's lifecycle.
        """
        # Keep a reference so factory methods (_create_pool_manager / _create_connector)
        # and subclasses can read extension fields like trace_configs.
        self.configuration = configuration

        # maxsize is number of requests to host that are allowed in parallel
        self.maxsize = configuration.connection_pool_maxsize

        # SSL context is built lazily (see _get_ssl_context) so that
        # constructing RESTClientObject never touches disk on the event loop.
        # It is entirely unused when an external `session` is supplied.
        self.ssl_context: Optional[ssl.SSLContext] = None
        self._ssl_context_lock: Optional[asyncio.Lock] = None

        self.proxy = configuration.proxy
        self.proxy_headers = configuration.proxy_headers

        retries = configuration.retries
        if retries is None:
            self._effective_retry_options = None
        elif isinstance(retries, aiohttp_retry.RetryOptionsBase):
            self._effective_retry_options = retries
        elif isinstance(retries, int):
            self._effective_retry_options = aiohttp_retry.ExponentialRetry(
                attempts=retries,
                factor=2.0,
                start_timeout=0.1,
                max_timeout=120.0
            )
        else:
            self._effective_retry_options = None

        # If an external session was supplied (e.g. HA's shared session), use
        # it directly and never build/own our own ClientSession.
        self._external_session = session is not None
        self.pool_manager: Optional[aiohttp.ClientSession] = session
        self.retry_client: Optional[aiohttp_retry.RetryClient] = None

    async def close(self) -> None:
        # Never close a session we don't own (e.g. Home Assistant's shared
        # session must stay alive for the rest of HA's lifetime).
        if self.pool_manager and not self._external_session:
            await self.pool_manager.close()
        if self.retry_client is not None:
            await self.retry_client.close()

    async def _get_ssl_context(self) -> ssl.SSLContext:
        """Build (once) the SSLContext off the event loop.

        ssl.create_default_context() reads the system trust store from disk
        the first time it's called, which is a blocking operation. We push
        that into the default executor so it never runs on HA's event loop.
        """
        if self.ssl_context is not None:
            return self.ssl_context

        if self._ssl_context_lock is None:
            self._ssl_context_lock = asyncio.Lock()

        async with self._ssl_context_lock:
            # Re-check in case another coroutine built it while we waited.
            if self.ssl_context is None:
                loop = asyncio.get_running_loop()
                self.ssl_context = await loop.run_in_executor(
                    None, self._build_ssl_context
                )
        return self.ssl_context

    def _build_ssl_context(self) -> ssl.SSLContext:
        """Blocking SSL context construction; only ever called via an executor."""
        ctx = ssl.create_default_context(
            cafile=self.configuration.ssl_ca_cert,
            cadata=self.configuration.ca_cert_data,
        )
        if self.configuration.cert_file:
            ctx.load_cert_chain(
                self.configuration.cert_file, keyfile=self.configuration.key_file
            )
        if not self.configuration.verify_ssl:
            ctx.check_hostname = False
            ctx.verify_mode = ssl.CERT_NONE
        return ctx

    async def _create_connector(self) -> aiohttp.TCPConnector:
        """Build the TCPConnector used by the ClientSession.

        Override in a subclass to customize DNS resolver, keepalive, etc.
        Only used when this client owns its ClientSession (no external
        session was supplied).
        """
        ssl_context = await self._get_ssl_context()
        kwargs: Dict[str, Any] = {
            "limit": self.maxsize,
            "ssl": ssl_context,
        }
        limit_per_host = getattr(self.configuration, "tcp_connector_limit_per_host", None)
        if limit_per_host is not None:
            kwargs["limit_per_host"] = limit_per_host
        return aiohttp.TCPConnector(**kwargs)

    async def _create_pool_manager(self) -> aiohttp.ClientSession:
        """Build the aiohttp.ClientSession used as the connection pool.

        Override in a subclass to fully customize the session (e.g. attach
        aiohttp.TraceConfig, swap json_serialize, etc.). Typed Configuration
        fields (trace_configs / client_session_kwargs) are read via getattr
        so older Configuration objects remain compatible.
        """
        extra = getattr(self.configuration, "client_session_kwargs", None)
        kwargs: Dict[str, Any] = {
            "connector": await self._create_connector(),
            "trust_env": True,
        }
        trace_configs = getattr(self.configuration, "trace_configs", None)
        if trace_configs is not None:
            kwargs["trace_configs"] = trace_configs
        if extra:
            kwargs.update(extra)
        return aiohttp.ClientSession(**kwargs)

    async def request(
        self,
        method,
        url,
        headers=None,
        body=None,
        post_params=None,
        _request_timeout=None
    ):
        """Execute request

        :param method: http request method
        :param url: http request url
        :param headers: http request headers
        :param body: request json body, for `application/json`
        :param post_params: request post parameters,
                            `application/x-www-form-urlencoded`
                            and `multipart/form-data`
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        """
        method = method.upper()
        assert method in [
            'GET',
            'HEAD',
            'DELETE',
            'POST',
            'PUT',
            'PATCH',
            'OPTIONS'
        ]

        if post_params and body:
            raise ApiValueError(
                "body parameter cannot be used with post_params parameter."
            )

        post_params = post_params or {}
        headers = headers or {}
        # url already contains the URL query string
        timeout = _request_timeout or 5 * 60

        if 'Content-Type' not in headers:
            headers['Content-Type'] = 'application/json'

        args = {
            "method": method,
            "url": url,
            "timeout": timeout,
            "headers": headers
        }

        if self.proxy:
            args["proxy"] = self.proxy
        if self.proxy_headers:
            args["proxy_headers"] = self.proxy_headers

        # For `POST`, `PUT`, `PATCH`, `OPTIONS`, `DELETE`
        if method in ['POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE']:
            if re.search('json', headers['Content-Type'], re.IGNORECASE):
                if body is not None:
                    body = json.dumps(body)
                if body is None and post_params:
                    body = json.dumps(dict(post_params))
                args["data"] = body
            elif headers['Content-Type'] == 'application/x-www-form-urlencoded':
                args["data"] = aiohttp.FormData(post_params)
            elif headers['Content-Type'] == 'multipart/form-data':
                # must del headers['Content-Type'], or the correct
                # Content-Type which generated by aiohttp
                del headers['Content-Type']
                data = aiohttp.FormData()
                for param in post_params:
                    k, v = param
                    if isinstance(v, tuple) and len(v) == 3:
                        data.add_field(
                            k,
                            value=v[1],
                            filename=v[0],
                            content_type=v[2]
                        )
                    else:
                        # Ensures that dict objects are serialized
                        if isinstance(v, dict):
                            v = json.dumps(v)
                        elif isinstance(v, int):
                            v = str(v)
                        data.add_field(k, v)
                args["data"] = data

            # Pass a `bytes` or `str` parameter directly in the body to support
            # other content types than Json when `body` argument is provided
            # in serialized form
            elif isinstance(body, str) or isinstance(body, bytes):
                args["data"] = body
            else:
                # Cannot generate the request from given parameters
                msg = """Cannot prepare a request message for provided
                         arguments. Please check that your arguments match
                         declared content type."""
                raise ApiException(status=0, reason=msg)

        pool_manager: Union[aiohttp.ClientSession, aiohttp_retry.RetryClient]

        # https pool manager
        if self.pool_manager is None:
            self.pool_manager = await self._create_pool_manager()
        pool_manager = self.pool_manager

        if self._effective_retry_options is not None and method in ALLOW_RETRY_METHODS:
            if self.retry_client is None:
                self.retry_client = aiohttp_retry.RetryClient(
                    client_session=self.pool_manager,
                    retry_options=self._effective_retry_options
                )
            pool_manager = self.retry_client

        r = await pool_manager.request(**args)

        return RESTResponse(r)